// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://quiz-sprint-tma.online/terms",
        "contact": {
            "name": "API Support",
            "url": "https://quiz-sprint-tma.online/support",
            "email": "support@quiz-sprint-tma.online"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/quiz": {
            "get": {
                "description": "Get a list of all available quizzes with basic information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quiz"
                ],
                "summary": "List all quizzes",
                "responses": {
                    "200": {
                        "description": "List of quizzes",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ListQuizzesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/quiz/session/{sessionId}/answer": {
            "post": {
                "description": "Submit an answer for a question in an active quiz session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quiz"
                ],
                "summary": "Submit an answer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Submit answer request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.SubmitAnswerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Answer result with correctness, points, and next question or final result",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.SubmitAnswerResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request, session completed, or already answered",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - user mismatch",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Session, question, or answer not found",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/quiz/{id}": {
            "get": {
                "description": "Get detailed quiz information including questions, answers (without correct answer indicators), and top 3 leaderboard scores",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quiz"
                ],
                "summary": "Get quiz details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quiz ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Quiz details with questions and top scores",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.GetQuizDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid quiz ID",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Quiz not found",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/quiz/{id}/leaderboard": {
            "get": {
                "description": "Get the leaderboard for a specific quiz with top scores",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quiz"
                ],
                "summary": "Get quiz leaderboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quiz ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of entries to return (default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Leaderboard entries",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.GetLeaderboardResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid quiz ID",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Quiz not found",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/quiz/{id}/start": {
            "post": {
                "description": "Create a new quiz session for a user and return the first question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quiz"
                ],
                "summary": "Start a quiz session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quiz ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Start quiz request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.StartQuizRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Quiz session started with first question",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.StartQuizResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or quiz ID",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Quiz not found",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Active session already exists",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_infrastructure_http_handlers.AnswerDTO": {
            "type": "object",
            "required": [
                "id",
                "position",
                "text"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_http_handlers.ErrorDetail": {
            "type": "object",
            "required": [
                "code",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_http_handlers.ErrorResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "$ref": "#/definitions/internal_infrastructure_http_handlers.ErrorDetail"
                }
            }
        },
        "internal_infrastructure_http_handlers.FinalResultDTO": {
            "type": "object",
            "required": [
                "correctCount",
                "maxScore",
                "passed",
                "percentage",
                "questionsCount",
                "totalScore"
            ],
            "properties": {
                "correctCount": {
                    "type": "integer"
                },
                "maxScore": {
                    "type": "integer"
                },
                "passed": {
                    "type": "boolean"
                },
                "percentage": {
                    "type": "integer"
                },
                "questionsCount": {
                    "type": "integer"
                },
                "totalScore": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_http_handlers.GetLeaderboardResponse": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_http_handlers.LeaderboardEntryDTO"
                    }
                }
            }
        },
        "internal_infrastructure_http_handlers.GetQuizDetailsData": {
            "type": "object",
            "required": [
                "quiz",
                "topScores"
            ],
            "properties": {
                "quiz": {
                    "$ref": "#/definitions/internal_infrastructure_http_handlers.QuizDetailDTO"
                },
                "topScores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_http_handlers.LeaderboardEntryDTO"
                    }
                }
            }
        },
        "internal_infrastructure_http_handlers.GetQuizDetailsResponse": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_infrastructure_http_handlers.GetQuizDetailsData"
                }
            }
        },
        "internal_infrastructure_http_handlers.LeaderboardEntryDTO": {
            "type": "object",
            "required": [
                "completedAt",
                "rank",
                "score",
                "userId",
                "username"
            ],
            "properties": {
                "completedAt": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "userId": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_http_handlers.ListQuizzesResponse": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_http_handlers.QuizDTO"
                    }
                }
            }
        },
        "internal_infrastructure_http_handlers.QuestionDTO": {
            "type": "object",
            "required": [
                "answers",
                "id",
                "points",
                "position",
                "text"
            ],
            "properties": {
                "answers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_http_handlers.AnswerDTO"
                    }
                },
                "id": {
                    "type": "string"
                },
                "points": {
                    "type": "integer"
                },
                "position": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_http_handlers.QuizDTO": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "passingScore",
                "questionsCount",
                "timeLimit",
                "title"
            ],
            "properties": {
                "createdAt": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "passingScore": {
                    "type": "integer"
                },
                "questionsCount": {
                    "type": "integer"
                },
                "timeLimit": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_http_handlers.QuizDetailDTO": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "passingScore",
                "questions",
                "timeLimit",
                "title"
            ],
            "properties": {
                "createdAt": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "passingScore": {
                    "type": "integer"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_http_handlers.QuestionDTO"
                    }
                },
                "timeLimit": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_http_handlers.SessionDTO": {
            "type": "object",
            "required": [
                "currentQuestion",
                "id",
                "quizId",
                "score",
                "startedAt",
                "status",
                "userId"
            ],
            "properties": {
                "completedAt": {
                    "type": "integer"
                },
                "currentQuestion": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "quizId": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "startedAt": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_http_handlers.StartQuizData": {
            "type": "object",
            "required": [
                "firstQuestion",
                "session",
                "timeLimit",
                "totalQuestions"
            ],
            "properties": {
                "firstQuestion": {
                    "$ref": "#/definitions/internal_infrastructure_http_handlers.QuestionDTO"
                },
                "session": {
                    "$ref": "#/definitions/internal_infrastructure_http_handlers.SessionDTO"
                },
                "timeLimit": {
                    "type": "integer"
                },
                "totalQuestions": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_http_handlers.StartQuizRequest": {
            "type": "object",
            "required": [
                "userId"
            ],
            "properties": {
                "userId": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_http_handlers.StartQuizResponse": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_infrastructure_http_handlers.StartQuizData"
                }
            }
        },
        "internal_infrastructure_http_handlers.SubmitAnswerData": {
            "type": "object",
            "required": [
                "correctAnswerId",
                "isCorrect",
                "isQuizCompleted",
                "pointsEarned",
                "totalScore"
            ],
            "properties": {
                "correctAnswerId": {
                    "type": "string"
                },
                "finalResult": {
                    "$ref": "#/definitions/internal_infrastructure_http_handlers.FinalResultDTO"
                },
                "isCorrect": {
                    "type": "boolean"
                },
                "isQuizCompleted": {
                    "type": "boolean"
                },
                "nextQuestion": {
                    "$ref": "#/definitions/internal_infrastructure_http_handlers.QuestionDTO"
                },
                "pointsEarned": {
                    "type": "integer"
                },
                "totalScore": {
                    "type": "integer"
                }
            }
        },
        "internal_infrastructure_http_handlers.SubmitAnswerRequest": {
            "type": "object",
            "required": [
                "answerId",
                "questionId",
                "userId"
            ],
            "properties": {
                "answerId": {
                    "type": "string"
                },
                "questionId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "internal_infrastructure_http_handlers.SubmitAnswerResponse": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_infrastructure_http_handlers.SubmitAnswerData"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Quiz Sprint API",
	Description:      "Quiz Sprint TMA Backend API - A Telegram Mini App for interactive quizzes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
