package shared

import "github.com/google/uuid"

// UserID represents a Telegram user identifier
type UserID struct {
	value string
}

// NewUserID creates a new UserID
func NewUserID(value string) (UserID, error) {
	if value == "" {
		return UserID{}, ErrInvalidUserID
	}

	return UserID{value: value}, nil
}

// String returns the string representation
func (id UserID) String() string {
	return id.value
}

// Equals checks equality with another UserID
func (id UserID) Equals(other UserID) bool {
	return id.value == other.value
}

// IsZero checks if the ID is zero value
func (id UserID) IsZero() bool {
	return id.value == ""
}

// UUID-based ID (for entities generated by backend)
type ID struct {
	value uuid.UUID
}

// NewID creates a new UUID-based ID
func NewID() ID {
	return ID{value: uuid.New()}
}

// NewIDFromString creates an ID from string
func NewIDFromString(value string) (ID, error) {
	if value == "" {
		return ID{}, ErrInvalidID
	}

	id, err := uuid.Parse(value)
	if err != nil {
		return ID{}, ErrInvalidID
	}

	return ID{value: id}, nil
}

// String returns the string representation
func (id ID) String() string {
	return id.value.String()
}

// Equals checks equality
func (id ID) Equals(other ID) bool {
	return id.value == other.value
}

// IsZero checks if zero value
func (id ID) IsZero() bool {
	return id.value == uuid.Nil
}
